name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "YukkiMusic/requirements.txt" ]; then
            # تثبيت المكتبات من requirements.txt
            pip install -r YukkiMusic/requirements.txt || {
              echo "خطأ في تثبيت المكتبات، سوف أقوم بتحديث المكتبات."
              pip install --upgrade --force-reinstall -r YukkiMusic/requirements.txt
            }
          else
            echo "requirements.txt غير موجود في دليل YukkiMusic!"
            exit 1
          fi

      - name: Check and update requirements
        run: |
          pip freeze > YukkiMusic/requirements.txt

      - name: Run bot
        run: python YukkiMusic/__main__.py
