name: Run YukkiMusic Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || pip install pyrogram pytgcalls

      - name: Verify dependencies
        run: |
          pip freeze > requirements.txt

      - name: Run bot
        run: |
          python YukkiMusic/__main__.py
