name: Run YukkiMusic Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install required packages
      run: |
        if [ -f "YukkiMusic/requirements.txt" ]; then
          pip install -r YukkiMusic/requirements.txt || {
            echo "Fixing dependencies in requirements.txt..."
            sed -i 's/pytgcalls==1.2.0/pytgcalls>=0.0.2,<2.0.0/' YukkiMusic/requirements.txt
            pip install -r YukkiMusic/requirements.txt
          }
        else
          echo "requirements.txt not found in YukkiMusic directory!"
          exit 1
        fi

    - name: Run the bot
      run: python YukkiMusic/__main__.py
