name: Deploy Telegram Bot

on:
  push:
    branches:
      - main  # أو الفرع الذي ترغب في تتبعه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # خطوة لعمل checkout للكود
      - name: Checkout code
        uses: actions/checkout@v2

      # خطوة لإعداد Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # تأكد من أن الإصدار يطابق الإصدار الذي تستخدمه

      # خطوة لتثبيت الاعتماديات
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # خطوة لطباعة هيكل المجلد (اختياري)
      - name: List files
        run: ls -R

      # خطوة لتشغيل البوت
      - name: Run bot
        env:
          Bot_Token: ${{ secrets.Bot_Token }}  # استخدم السر الخاص بالتوكن
        run: python -m YukkiMusic.__main__  # تأكد من أن المسار صحيح
