name: Run YukkiMusic Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install required packages
      run: |
        pip install aiofiles
        pip install "aiohttp>=3.9.3,<4.0"
        pip install dnspython
        pip install ffmpeg-python
        pip install gitpython
        pip install hachoir
        pip install heroku3
        pip install lyricsgenius
        pip install "motor>=3.1,<4.0"
        pip install "pymongo>=4.5,<5.0"
        pip install flask
        pip install flask_restful
        pip install pillow
        pip install psutil
        pip install "ntgcalls>=1.2.0,<1.3.0"
        pip install pykeyboard
        pip install pyrogram==1.3.5
        pip install pytgcalls  # تثبيت أحدث إصدار
        pip install TgCrypto
        pip install python-dotenv
        pip install pyyaml==5.3.1
        pip install requests
        pip install telegraph
        pip install gpytranslate
        pip install speedtest-cli
        pip install spotipy
        pip install tgcrypto
        pip install Flask==2.2.2
        pip install gunicorn==21.2.0
        pip install youtube-search
        pip install youtube-search-python
        pip install "multidict>=4.5,<7.0"
        pip install "yarl>=1.0,<2.0"
        pip install git+https://github.com/yt-dlp/yt-dlp.git
        pip install git+https://github.com/joetats/youtube_search@master
        pip install git+https://github.com/alexmercerind/youtube-search-python@main

    - name: List installed packages
      run: pip list  # للتأكد من تثبيت المكتبات

    - name: Run the bot
      run: python YukkiMusic/__main__.py
